[tools]
node = '22.14.0'
#java = ['22.0.1', '11.0.2']
python = ['3.11']
uv = "latest"
gh = "latest"
jq = "latest"
neovim = "0.12.4"
#php = ['8.2']
go = ['1.21']
php = "8.4.25"
#ruby = ['3.2']
#rust = ['1.92.0']
